const articles = [
  {
    id: 1,
    date: '2013-01-13',
    title:
      'Validation of data mining models by comparing with conventional methods for dental age estimation in Korean juveniles and young adults',
    subject: 'research',
    tag: 'data-mining',
    img: '/pages/research-article/article-0001/public/figure/fig1.webp',
    des: 'Teeth are known to be the most accurate age indicators of human body and are frequently applied in forensic age estimation. We aimed to validate data mining-based dental age estimation, by comparing the accuracy of the estimation and classification performance of 18-year thresholds with conventional methods and with data mining-based age estimatio.',
    author: 'Akiko Kumagai, Seoi Jeong, Daeyoun Kim, Hyoun-Joong Kong, Sehyun Oh & Sang-Seob Lee',
    link: '/pages/research-article/article-0001/article-0001.html',
  },
  {
    id: 2,
    date: '2022-10-14',
    title: 'Diagnostic performance of convolutional neural networks for dental sexual dimorphism',
    subject: 'research',
    tag: 'diagnostic',
    img: '/pages/research-article/article-0002/public/figure/figure2.1.webp',
    des: 'Convolutional neural networks (CNN) led to important solutions in the field of Computer Vision. More recently, forensic sciences benefited from the resources of artificial intelligence, especially in procedures that normally require operator-dependent steps.',
    author:
      'Ademir Franco, Lucas Porto, Dennis Heng, Jared Murray, Anna Lygate, Raquel Franco, Juliano Bueno, Marilia Sobania, Márcio M. Costa, Luiz R. Paranhos, Scheila Manica & André Abade',
    link: '/pages/research-article/article-0002/article-0002.html',
  },
  {
    id: 3,
    date: '2023-01-13',
    title:
      'Boosting algorithm improves the accuracy of juvenile forensic dental age estimation in southern China population',
    subject: 'research',
    tag: 'diagnostic',
    img: '/pages/research-article/article-0003/public/figure/fig1.webp',
    des: 'The classification performance of the 18-year threshold was also similar between the conventional method and the data mining models. Thus, conventional methods can be replaced by data mining models in forensic age estimation using second and third molar maturity of Korean juveniles and young adults.',
    author: 'Akiko Kumagai, Seoi Jeong, Daeyoun Kim, Hyoun-Joong Kong, Sehyun Oh & Sang-Seob Lee',
    link: '/pages/research-article/article-0003/article-0001.html',
  },

  {
    id: 4,
    date: '2021-08-17',
    title:
      'Population affinity and variation of sexual dimorphism in three-dimensional facial forms: comparisons between Turkish and Japanese populations',
    subject: 'research',
    tag: 'data-mining',
    img: '/pages/research-article/article-0004/public/figure/fig1.webp',
    des: 'The classification performance of the 18-year threshold was also similar between the conventional method and the data mining models. Thus, conventional methods can be replaced by data mining models in forensic age estimation using second and third molar maturity of Korean juveniles and young adults.',
    author: 'Akiko Kumagai, Seoi Jeong, Daeyoun Kim, Hyoun-Joong Kong, Sehyun Oh & Sang-Seob Lee',
    link: '/pages/research-article/article-0004/article-0001.html',
  },

  {
    id: 5,
    date: '2023-01-13',
    title: 'The use of anterior gold basket crowns among remote Amazonian communities',
    subject: 'research',
    tag: 'restoration',
    img: '/pages/research-article/article-0005/public/figure/fig1.webp',
    des: 'Highlights the dental implications of poorly constructed restorations.',
    author: 'Akiko Kumagai, Seoi Jeong, Daeyoun Kim, Hyoun-Joong Kong, Sehyun Oh & Sang-Seob Lee',
    link: '/pages/research-article/article-0005/article-0001.html',
  },
  {
    id: 6,
    date: '2023-01-13',
    title:
      'The reciprocal jaw-muscle reflexes elicited by anterior- and back-tooth-contacts—a perspective to explain the control of the masticatory muscles',
    subject: 'research',
    tag: 'biology',
    img: '/pages/research-article/article-0006/public/figure/fig1.webp',
    des: 'The classification performance of the 18-year threshold was also similar between the conventional method and the data mining models. Thus, conventional methods can be replaced by data mining models in forensic age estimation using second and third molar maturity of Korean juveniles and young adults.',
    author: 'Akiko Kumagai, Seoi Jeong, Daeyoun Kim, Hyoun-Joong Kong, Sehyun Oh & Sang-Seob Lee',
    link: '/pages/research-article/article-0006/article-0001.html',
  },
  {
    id: 7,
    date: '2023-01-13',
    title: 'Case report: A medieval case of molar-incisor-hypomineralisation',
    subject: 'research',
    tag: 'biology',
    img: '/pages/research-article/article-0007/public/figure/fig1.webp',
    des: 'The classification performance of the 18-year threshold was also similar between the conventional method and the data mining models. Thus, conventional methods can be replaced by data mining models in forensic age estimation using second and third molar maturity of Korean juveniles and young adults.',
    author: 'Akiko Kumagai, Seoi Jeong, Daeyoun Kim, Hyoun-Joong Kong, Sehyun Oh & Sang-Seob Lee',
    link: '/pages/research-article/article-0007/article-0001.html',
  },
  {
    id: 8,
    date: '2017-11-24',
    title: 'Teeth as pearls of wisdom',
    subject: 'research',
    tag: 'biology',
    img: '/pages/research-article/article-0008/public/figure/fig1.webp',
    des: 'The classification performance of the 18-year threshold was also similar between the conventional method and the data mining models. Thus, conventional methods can be replaced by data mining models in forensic age estimation using second and third molar maturity of Korean juveniles and young adults.',
    author: 'G. H. Sperber ',
    link: '/pages/research-article/article-0008/article-0001.html',
  },
  {
    id: 9,
    date: '2017-11-24',
    title:
      'Upper anterior tooth dimensions in a young-adult Indian population in the UK: implications for aesthetic dentistry',
    subject: 'research',
    tag: 'biology',
    img: '/pages/research-article/article-0009/public/figure/fig1.webp',
    des: 'Suggests that successful outcomes in aesthetic dentistry depend to a large degree on knowledge of tooth dimensions, relationships and proportions.',
    author: 'T. B. Shetty, F. Beyuo & N. H. F. Wilson ',
    link: '/pages/research-article/article-0009/article-0001.html',
  },
  {
    id: 10,
    date: '2015-06-26',
    title: 'Reduction of temporomandibular joint dislocation: an ancient technique that has stood the test of time',
    subject: 'research',
    tag: 'diagnostic',
    img: '/pages/research-article/article-0010/public/figure/fig1.webp',
    des: 'Reviews the mechanism and common causes of temporomandibular joint (TMJ) dislocation.',
    author: 'R. J. Forshaw ',
    link: '/pages/research-article/article-0010/article-0001.html',
  },
  {
    id: 11,
    date: '2023-01-13',
    title:
      'A highly elastic absorbable monofilament suture fabricated from poly(3-hydroxybutyrate-co-4-hydroxybutyrate)',
    subject: 'research',
    tag: 'data-mining',
    img: '/pages/research-article/article-0011/public/figure/fig1.webp',
    des: 'The classification performance of the 18-year threshold was also similar between the conventional method and the data mining models. Thus, conventional methods can be replaced by data mining models in forensic age estimation using second and third molar maturity of Korean juveniles and young adults.',
    author: 'Atsuhiko Murayama, Hidemasa Yoneda, Akira Maehara, Noriyuki Shiomi & Hitoshi Hirata ',
    link: '/pages/research-article/article-0011/article-0001.html',
  },
  {
    id: 12,
    date: '2023-02-25',
    title: 'Effects of tongue right positioner use on tongue pressure: a pilot study',
    subject: 'research',
    tag: 'diagnostic',
    img: '/pages/research-article/article-0012/public/figure/fig1.webp',
    des: 'The effectiveness of the tongue right positioner (TRP) use on oral and swallowing functions remains unclear. To investigate the effects of TRP use on tongue function in patients with dysphagia.',
    author:
      'Ryosuke Yanagida, Koji Hara, Chizuru Namiki, Takuma Okumura, Akino Saiki, Kazuharu Nakagawa, Kohei Yamaguchi, Kanako Yoshimi, Ayako Nakane, Jean-Michel Mauclaire & Haruka Tohara ',
    link: '/pages/research-article/article-0012/article-0001.html',
  },
  {
    id: 13,
    date: '2021-05-05',
    title: 'Does Vitamin C and Caffeine Affect Local Anesthesia Before a Dental Procedure?',
    subject: 'patientEdu',
    tag: 'technology',
    img: 'https://www.health.com/thmb/9LVMm1plFPYKBih543QRnl6dAks=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/dentist-vitamin-c-GettyImages-188012190-89f51ecdcdeb4792b1484b2fa91ac534.jpg',
    des: 'Regular visits to a dentist are part of having good oral health and will aid your overall health. But a post on the social media sharing site TikTok has some people wondering about their safety during that dental visit.',
    author: 'Claire Gillespie',
    link: '/pages/patientedu-article/article-0002/patientedu-0001.html',
  },
  {
    id: 14,
    date: '2022-12-22',
    title: 'You May One Day Listen With Your Mouth',
    subject: 'patientEdu',
    tag: 'advice',
    img: 'https://www.health.com/thmb/WViJHuEWMfM6MNGRzQcqCdmuuAA=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Dental-Care-Diabetes-Heart-Disease-GettyImages-904657730-2000-d106253af9b54ceba2bad7031cdfc657.jpg',
    des: 'You could one day wear hearing aids in your mouth thanks to dental implant technology, according to researchers from the Department of Prosthodontics',
    author: 'Medscape Staff',
    link: '/pages/patientedu-article/article-0001/patientedu-0001.html',
  },
  {
    id: 15,
    date: '2022-08-17',
    title: 'What Are Salivary Stones—Sialoliths?',
    subject: 'patientEdu',
    tag: 'symptom',
    img: 'https://www.health.com/thmb/X84eQ24wQPtmaFIFmvcunukV-BA=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/tongue-AdobeStock_96017191-8c765d78e6484e01a8c34305a3f3003a.jpg',
    des: 'You could one day wear hearing aids in your mouth thanks to dental implant technology, according to researchers from the Department of Prosthodontics',
    author: 'Medscape Staff',
    link: '/pages/patientedu-article/article-0001/patientedu-0001.html',
  },
  {
    id: 16,
    date: '2023-02-11',
    title: '13 Reasons Your Tooth Hurts',
    subject: 'patientEdu',
    tag: 'advice',
    img: '  https://imagesvc.meredithcorp.io/v3/jumpstartpure/image/?url=https%3A%2F%2Fcf-images.us-east-1.prod.boltdns.net%2Fv1%2Fstatic%2F1125866826%2F8b6381d2-837e-403c-9713-8f4618e96bc5%2Fa2fa6b75-bf0a-4534-a17d-518c316f194a%2F1280x720%2Fmatch%2Fimage.jpg',
    des: 'You could one day wear hearing aids in your mouth thanks to dental implant technology, according to researchers from the Department of Prosthodontics',
    author: 'Rachel Swalin and Sarah Klein',
    link: '/pages/patientedu-article/article-0004/patientedu-0001.html',
  },
  {
    id: 17,
    date: '2023-11-06',
    title: 'The 10 Best Mouthwashes of 2023',
    subject: 'patientEdu',
    tag: 'product',
    img: ' https://www.health.com/thmb/Si6lFVXBBkH2NWNFnTTHxYlVa6A=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/BestMouthwashforaHealthierMouthtout-7a7a3aa9639a4abab4b08be4e6fa3b28.jpg',
    des: 'You could one day wear hearing aids in your mouth thanks to dental implant technology, according to researchers from the Department of Prosthodontics',
    author: 'Rachael Schultz',
    link: '/pages/patientedu-article/article-0005/patientedu-0001.html',
  },
  {
    id: 18,
    date: '2022-11-14',
    title: 'What Causes a White Tongue? Here’s What Dentists Want You To Know',
    subject: 'patientEdu',
    tag: 'advice',
    img: ' https://www.health.com/thmb/O5nzxSHWmGpp_CRDwpkTTzRdxXM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/tongue-GettyImages-1292019438-7c934e39c6ad4d32b6842e0c735b3e63.jpg',
    des: 'For the most part, a white tongue is pretty benign—but sometimes it can signal a bigger oral health issue.',
    author: 'Lauren Krouse',
    link: '/pages/patientedu-article/article-0006/patientedu-0001.html',
  },
  {
    id: 19,
    date: '2023-01-20',
    title: 'What Is Palatal Petechiae?',
    subject: 'patientEdu',
    tag: 'symptom',
    img: ' https://imagesvc.meredithcorp.io/v3/jumpstartpure/image/?url=https%3A%2F%2Fcf-images.us-east-1.prod.boltdns.net%2Fv1%2Fstatic%2F1125866826%2F96048885-a224-4c47-8d8d-54b35e2522ad%2F77209978-f53b-4874-9530-974994dfcd64%2F1280x720%2Fmatch%2Fimage.jpg',
    des: 'It mostly affects the softest top part of your mouth.',
    author: 'Reven Widener',
    link: '/pages/patientedu-article/article-0007/patientedu-0001.html',
  },
  {
    id: 20,
    date: '2021-01-11',
    title: 'Searing Toothache Misdiagnosed by Doctors, Turns Out to Be Cancer',
    subject: 'patientEdu',
    tag: 'symptom',
    img: 'https://imagesvc.meredithcorp.io/v3/jumpstartpure/image/?url=https%3A%2F%2Fcf-images.us-east-1.prod.boltdns.net%2Fv1%2Fjit%2F1125866826%2F01b77575-f015-4134-943b-66155bdb291f%2Fmain%2F1280x720%2F6m7s690ms%2Fmatch%2Fimage.jpg',
    des: 'A faulty biopsy hid the truth about her cancer.',
    author: 'Taylyn Washington-Harmon',
    link: '/pages/patientedu-article/article-0008/patientedu-0001.html',
  },
  {
    id: 21,
    date: '2020-01-08',
    title: "Black Hairy Tongue Is a Legitimate Condition–but It's Not as Scary as It Looks",
    subject: 'patientEdu',
    tag: 'symptom',
    img: 'https://imagesvc.meredithcorp.io/v3/jumpstartpure/image/?url=https%3A%2F%2Fcf-images.us-east-1.prod.boltdns.net%2Fv1%2Fstatic%2F1125866826%2F9b0c6784-179d-46c4-a28d-936445295fa7%2F2eb7028c-d3ab-4eb3-8afa-407cd095768b%2F1280x720%2Fmatch%2Fimage.jpg',
    des: 'A new report details the case of a 55-year-old woman whose tongue became discolored and furry-looking after a car crash.',
    author: 'Sarah Klein',
    link: '/pages/patientedu-article/article-0009/patientedu-0001.html',
  },
  {
    id: 22,
    date: '2018-05-02',
    title: 'Why Your Breath Might Start to Smell Worse as You Get Older',
    subject: 'patientEdu',
    tag: 'advice',
    img: 'https://th-thumbnailer.cdn-si-edu.com/a_lz4543fhbK1KxGiKff_IGgnvU=/1000x750/filters:no_upscale():focal(853x419:854x420)/https://tf-cmsv2-smithsonianmag-media.s3.amazonaws.com/filer/6e/5d/6e5d167c-a913-4f99-92fd-4b236341f405/gettyimages-1039521428_web.jpg',
    des: 'Everyone gets bad breath from time to time, but the odor—technically called halitosis—can be particularly strong in older adults. ',
    author: 'Sarah Klein',
    link: '/pages/patientedu-article/article-0010/patientedu-0001.html',
  },
  {
    id: 23,
    date: '2021-09-02',
    title: 'Ultimate Clean',
    subject: 'products',
    tag: 'electric',
    img: '/pages/Products/public/electric-access.png',
    des: 'Establish habits of changing brush head regularly ',
    link: '/pages/product-item/products-electric-003/products-003.html',
  },
  {
    id: 24,
    date: '2022-06-09',
    title: 'iO 6',
    subject: 'products',
    tag: 'electric',
    img: '/pages/Products/public/electric-brushes.png',
    des: 'Clinically Proven technology with a wealth of scientific evidence',
    link: '/pages/product-item/products-electric-001/products-001.html',
  },
  {
    id: 25,
    date: '2022-12-12',
    title: 'iO 8',
    subject: 'products',
    tag: 'electric',
    img: '/pages/Products/public/io8-card.png',
    des: 'Oscillation rotation and microvibrations for a sensational clean',
    link: '/pages/product-item/products-electric-002/products-001.html',
  },
  {
    id: 26,
    date: '2022-09-12',
    title: 'Kid 3+',
    subject: 'products',
    tag: 'kids',
    img: '/pages/Products/public/special-for-kids.png',
    des: 'The Scientific Evidence of Strong Teeth Strong Kids',
    link: '/pages/product-item/products-kids-001/products-002.html',
  },
  {
    id: 27,
    date: '2022-06-05',
    title: 'Junior 6+',
    subject: 'products',
    tag: 'kids',
    img: '/pages/Products/public/junior6-card.png',
    des: 'Achieving good plaque control presents a significant challenge for children',
    link: '/pages/product-item/products-kids-002/products-002-kids.html',
  },
  {
    id: 28,
    date: '2022-12-05',
    title: 'Teens 12+',
    subject: 'products',
    tag: 'kids',
    img: '/pages/Products/public/teens12-card.png',
    des: 'Teach your kids good dental habits for life with Oral-B',
    link: '/pages/product-item/products-kids-003/products-002-kids2.html',
  },
  {
    id: 29,
    date: '2022-03-07',
    title: 'Crest Gum Detoxify',
    subject: 'products',
    tag: 'toothpaste',
    img: '/pages/Products/public/detoxify-card.png',
    des: 'The scientific evidence behind Stabilised Stannous Fluoride',
    link: '/pages/product-item/products-toothpaste-001/products-004.html',
  },
  {
    id: 30,
    date: '2022-07-09',
    title: 'Crest 3DWhite',
    subject: 'products',
    tag: 'toothpaste',
    img: '/pages/Products/public/tooth-pastes.png',
    des: 'Experience the power of nature with our all-natural toothpaste products',
    link: '/pages/product-item/products-toothpaste-002/products-004-toothpaste.html',
  },
  {
    id: 31,
    date: '2022-10-01',
    title: 'Crest Pro-Health',
    subject: 'products',
    tag: 'toothpaste',
    img: '/pages/Products/public/pro-health-card.png',
    des: 'Stannous Fluoride actions on plaque regrowth',
    link: '/pages/product-item/products-toothpaste-003/products-004-toothpaste2.html',
  },
];
