const articles = [
  {
    date: '2013-01-13',
    title:
      'Validation of data mining models by comparing with conventional methods for dental age estimation in Korean juveniles and young adults',
    subject: 'research',
    tag: 'data-mining',
    img: '/pages/research-article/article-0001/public/figure/fig1.webp',
    des: 'Teeth are known to be the most accurate age indicators of human body and are frequently applied in forensic age estimation. We aimed to validate data mining-based dental age estimation, by comparing the accuracy of the estimation and classification performance of 18-year thresholds with conventional methods and with data mining-based age estimatio.',
    author: 'Akiko Kumagai, Seoi Jeong, Daeyoun Kim, Hyoun-Joong Kong, Sehyun Oh & Sang-Seob Lee',
    link: '/pages/research-article/article-0001/article-0001.html',
  },
  {
    date: '2022-10-14',
    title: 'Diagnostic performance of convolutional neural networks for dental sexual dimorphism',
    subject: 'research',
    tag: 'diagnostic',
    img: '/pages/research-article/article-0002/public/figure/figure2.1.webp',
    des: 'Convolutional neural networks (CNN) led to important solutions in the field of Computer Vision. More recently, forensic sciences benefited from the resources of artificial intelligence, especially in procedures that normally require operator-dependent steps.',
    author:
      'Ademir Franco, Lucas Porto, Dennis Heng, Jared Murray, Anna Lygate, Raquel Franco, Juliano Bueno, Marilia Sobania, Márcio M. Costa, Luiz R. Paranhos, Scheila Manica & André Abade',
    link: '/pages/research-article/article-0002/article-0002.html',
  },
  {
    date: '2023-01-13',
    title:
      'Boosting algorithm improves the accuracy of juvenile forensic dental age estimation in southern China population',
    subject: 'research',
    tag: 'diagnostic',
    img: '/pages/research-article/article-0003/public/figure/fig1.webp',
    des: 'The classification performance of the 18-year threshold was also similar between the conventional method and the data mining models. Thus, conventional methods can be replaced by data mining models in forensic age estimation using second and third molar maturity of Korean juveniles and young adults.',
    author: 'Akiko Kumagai, Seoi Jeong, Daeyoun Kim, Hyoun-Joong Kong, Sehyun Oh & Sang-Seob Lee',
    link: '/pages/research-article/article-0003/article-0001.html',
  },

  {
    date: '2021-08-17',
    title:
      'Population affinity and variation of sexual dimorphism in three-dimensional facial forms: comparisons between Turkish and Japanese populations',
    subject: 'research',
    tag: 'data-mining',
    img: '/pages/research-article/article-0004/public/figure/fig1.webp',
    des: 'The classification performance of the 18-year threshold was also similar between the conventional method and the data mining models. Thus, conventional methods can be replaced by data mining models in forensic age estimation using second and third molar maturity of Korean juveniles and young adults.',
    author: 'Akiko Kumagai, Seoi Jeong, Daeyoun Kim, Hyoun-Joong Kong, Sehyun Oh & Sang-Seob Lee',
    link: '/pages/research-article/article-0004/article-0001.html',
  },
  // FAKE
  {
    date: '2023-01-13',
    title: 'The use of anterior gold basket crowns among remote Amazonian communities',
    subject: 'research',
    tag: 'restoration',
    img: '/pages/research-article/article-0005/public/figure/fig1.webp',
    des: 'Highlights the dental implications of poorly constructed restorations.',
    author: 'Akiko Kumagai, Seoi Jeong, Daeyoun Kim, Hyoun-Joong Kong, Sehyun Oh & Sang-Seob Lee',
    link: '/pages/research-article/article-0005/article-0001.html',
  },
  {
    date: '2023-01-13',
    title:
      'The reciprocal jaw-muscle reflexes elicited by anterior- and back-tooth-contacts—a perspective to explain the control of the masticatory muscles',
    subject: 'research',
    tag: 'biology',
    img: '/pages/research-article/article-0006/public/figure/fig1.webp',
    des: 'The classification performance of the 18-year threshold was also similar between the conventional method and the data mining models. Thus, conventional methods can be replaced by data mining models in forensic age estimation using second and third molar maturity of Korean juveniles and young adults.',
    author: 'Akiko Kumagai, Seoi Jeong, Daeyoun Kim, Hyoun-Joong Kong, Sehyun Oh & Sang-Seob Lee',
    link: '/pages/research-article/article-0006/article-0001.html',
  },
  {
    date: '2023-01-13',
    title: 'Case report: A medieval case of molar-incisor-hypomineralisation',
    subject: 'research',
    tag: 'biology',
    img: '/pages/research-article/article-0007/public/figure/fig1.webp',
    des: 'The classification performance of the 18-year threshold was also similar between the conventional method and the data mining models. Thus, conventional methods can be replaced by data mining models in forensic age estimation using second and third molar maturity of Korean juveniles and young adults.',
    author: 'Akiko Kumagai, Seoi Jeong, Daeyoun Kim, Hyoun-Joong Kong, Sehyun Oh & Sang-Seob Lee',
    link: '/pages/research-article/article-0007/article-0001.html',
  },
  {
    date: '2017-11-24',
    title: 'Teeth as pearls of wisdom',
    subject: 'research',
    tag: 'biology',
    img: '/pages/research-article/article-0008/public/figure/fig1.webp',
    des: 'The classification performance of the 18-year threshold was also similar between the conventional method and the data mining models. Thus, conventional methods can be replaced by data mining models in forensic age estimation using second and third molar maturity of Korean juveniles and young adults.',
    author: 'G. H. Sperber ',
    link: '/pages/research-article/article-0008/article-0001.html',
  },
  {
    date: '2017-11-24',
    title:
      'Upper anterior tooth dimensions in a young-adult Indian population in the UK: implications for aesthetic dentistry',
    subject: 'research',
    tag: 'biology',
    img: '/pages/research-article/article-0009/public/figure/fig1.webp',
    des: 'Suggests that successful outcomes in aesthetic dentistry depend to a large degree on knowledge of tooth dimensions, relationships and proportions.',
    author: 'T. B. Shetty, F. Beyuo & N. H. F. Wilson ',
    link: '/pages/research-article/article-0009/article-0001.html',
  },
  {
    date: '2015-06-26',
    title: 'Reduction of temporomandibular joint dislocation: an ancient technique that has stood the test of time',
    subject: 'research',
    tag: 'diagnostic',
    img: '/pages/research-article/article-0010/public/figure/fig1.webp',
    des: 'Reviews the mechanism and common causes of temporomandibular joint (TMJ) dislocation.',
    author: 'R. J. Forshaw ',
    link: '/pages/research-article/article-0010/article-0001.html',
  },
  {
    date: '2023-01-13',
    title:
      'A highly elastic absorbable monofilament suture fabricated from poly(3-hydroxybutyrate-co-4-hydroxybutyrate)',
    subject: 'research',
    tag: 'data-mining',
    img: '/pages/research-article/article-0011/public/figure/fig1.webp',
    des: 'The classification performance of the 18-year threshold was also similar between the conventional method and the data mining models. Thus, conventional methods can be replaced by data mining models in forensic age estimation using second and third molar maturity of Korean juveniles and young adults.',
    author: 'Atsuhiko Murayama, Hidemasa Yoneda, Akira Maehara, Noriyuki Shiomi & Hitoshi Hirata ',
    link: '/pages/research-article/article-0011/article-0001.html',
  },
  {
    date: '2023-02-25',
    title: 'Effects of tongue right positioner use on tongue pressure: a pilot study',
    subject: 'research',
    tag: 'diagnostic',
    img: '/pages/research-article/article-0012/public/figure/fig1.webp',
    des: 'The effectiveness of the tongue right positioner (TRP) use on oral and swallowing functions remains unclear. To investigate the effects of TRP use on tongue function in patients with dysphagia.',
    author:
      'Ryosuke Yanagida, Koji Hara, Chizuru Namiki, Takuma Okumura, Akino Saiki, Kazuharu Nakagawa, Kohei Yamaguchi, Kanako Yoshimi, Ayako Nakane, Jean-Michel Mauclaire & Haruka Tohara ',
    link: '/pages/research-article/article-0012/article-0001.html',
  },
];
